# Generated by Django 4.2.4 on 2023-08-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_is_authenticated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='invited_users',
            new_name='inviter',
        ),
    ]
